### ISSUE TITLE
Imagem cafe não aparece no centro

### ISSUE THREAD

**Issue by helio2323** [SamyNandes/Coffee-Shop#1]
@SamyNandes 

Para que a imagem apareça no seu index.html só precisa substituir essa linha

`<div id="imagem"><img src="café1.jpg" alt=""></div>
`
para essa

`<div id="imagem"><img src="cafe.jpg" alt=""></div>
`

Outra dica é organizar seu projeto por pastas, seguindo a organização abaixo:

- Pasta Style > Coloque os arquivos de estilo (.CSS)
- Pasta Script > Coloque os arquivos de código (.JS)
- Pasta Assets > Coloque arquivos que compoem o projeto como (.JPG ou .PNG)

**Comment by SamyNandes** [comment]
Issue resolvido. Obrigado pela dica e pela força! 👍
